### ISSUE TITLE
Following crash comes, when I open camera in Android app

### ISSUE THREAD

**Issue by Ashish-sipl** [Luca96/dlib-for-android#10]
com.tzutalin.dlibtest A/libc: Fatal signal 6 (SIGABRT), code -6 in tid 23803 (utalin.dlibtest)

Kindly help me to resolve the issue

**Comment by Luca96** [comment]
Hi @Ashish-sipl, 
I'm sorry but I don't understand your issue. Could you detail your problem more?
Have you compiled Dlib by using [dlib-for-android](https://github.com/Luca96/dlib-for-android)?
