### ISSUE TITLE
Getting in touch privately 

### ISSUE THREAD

**Issue by natario1** [Luca96/dlib-for-android#11]
Hi @Luca96 ! 
This is not an issue, I would just like to get in touch with you. Any chance you could provide an e-mail? Or send one to me just to start the conversation - you can find mine in my profile page.
Thanks!

**Comment by Luca96** [comment]
Hi @natario1, of course you can contact me. Here is my email: `luca.anzalone.dev@gmail.com`.

**Comment by natario1** [comment]
Done - thanks ! :-)
